on: [push]

jobs:
  jscrambler_job:
    runs-on: ubuntu-latest
    name: A job to obfuscate code
    steps:
      - uses: actions/checkout@v3
      - name: Test Jscrambler Action
        id: jscrambler
        uses: ./
        with:
          application-id: '123abc987zyx'
          secret-key: ${{ secrets.JSCRAMBLER_SECRET_KEY }}
          access-key: ${{ secrets.JSCRAMBLER_ACCESS_KEY }}
          files-src: |
            a
            b
      # Use the output from the `hello` step
      - name: Get the output protection_id
        run: echo "Your protection was successful. ${{ steps.jscrambler.outputs.protection-id }}"
